---
title: "Sensor_Plotting"
output: html_document
date: "2025-11-24"
---


## read in packages and data

```{r}
#packages 
library(tidyverse)

#read in data
sensors <- read_csv("../Data/sensors_joined.csv") 
 

```


all variables by date plot 

```{r}

sensors |> 
  # filter(!Site %in% c(50,88,90)) |> #If wanting to zoom in shallow sites
  select(-DO_mgL) |> 
  pivot_longer(-c(1:9)) |> 
  # filter(name == "Temp_C") |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m,
             #shape = factor(Site_Class, levels = c("Stream", "Pool", "Cove", "Pelagic"))
             ))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  facet_grid(name~Date, scales = "free_y")+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ #c(250, 750)
  #scale_shape_manual(values = c(24, 22, 21, 25))+ #18, 15, 16, 17
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15, 20))


```



 
## MS figures 


Highlight temp differences by date in shallower sites

```{r}
### Date levels
levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

##same format as below
sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = Temp_C))+
  geom_hline(yintercept = 0, color = "blue")+ # line for surface of the water
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #Line for dry reach; color gets rid of border
    geom_line(aes(y = Max_Depth_Site_m+0.1), color = "brown")+ #line for max depth
  facet_wrap(~factor(Date1, levels = levels_db), nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  theme_bw()+ theme(legend.position = "right", text = element_text(size = 14),
                    legend.text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "Temp \n (C)")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  scale_fill_distiller(palette = "Spectral", direction = -1) #direction flips value order so red is higher
  # scale_fill_gradient(low = "blue",  high ="red")
  #scale_fill_gradient2(low = "red",  high ="blue",  midpoint = 80,  guide = "colourbar")



##lines 
b1_c1_tempprofiles <- sensors |> 
  filter(!Site %in% c(50,88,90, 100, 101)) |> 
     mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Temp_C, y = Depth_m, color = factor(Date1, levels = levels_db) ))+
    facet_wrap(~factor(Site_code), scales = "fixed", ncol = 1)+
  geom_point(size =2)+ #need shape here if not doing site type
  geom_line(orientation = "y")+
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  scale_x_continuous(breaks = c(5,10,15,20,25,30))+
  theme_bw()+ theme(legend.position = "right", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Temp (C)", fill = element_blank(),
       y = "Depth (m)", color = "Sampling Date")+
    scale_color_brewer(palette = "Spectral", direction = -1) #direction flips value order so red is higher

b1_c1_tempprofiles

# plotly::ggplotly(b1_c1_tempprofiles)
# 
# ggsave("../Figures/TempProfiles_B1-C1.png", b1_c1_tempprofiles, width = 5, height = 5, units = "in")

#get temp differences to determine startificaiton here
sensors |> 
  filter(!Site %in% c(100, 101)) |> 
  select(Site, Site_code, Date, Depth_m, Temp_C) |> 
  group_by(Site_code, Date) |> 
  mutate(Strat_diff = max(Temp))
  


```




Stream to C1 for Main MS

```{r}

### Date levels
levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

#### COnd
summary(sensors$SpCond_uScm)

cond_S1_C1 <- sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = SpCond_uScm))+
  geom_hline(yintercept = 0, color = "blue")+ # line for surface of the water
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #Line for dry reach; color gets rid of border
    geom_line(aes(y = Max_Depth_Site_m+0.1), color = "brown")+ #line for max depth
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "Sp. Cond (uS/cm)")+ # can use \n to break the text
 scale_fill_distiller(palette = "Spectral", direction = -1)

cond_S1_C1

#### Temp
summary(sensors$Temp_C)

temp_S1_C1 <- sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = Temp_C))+
  geom_hline(yintercept = 0, color = "blue")+ # line for surface of the water
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #Line for dry reach; color gets rid of border
    geom_line(aes(y = Max_Depth_Site_m+0.1), color = "brown")+ #line for max depth
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "Temp (C)")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
  scale_fill_distiller(palette = "Spectral", direction = -1)


temp_S1_C1

#### DO
summary(sensors$DOsat_percent)

do_S1_C1 <- sensors |> 
  filter(!Site %in% c(50,88,90)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = Depth_m, fill = DOsat_percent))+
  geom_hline(yintercept = 0, color = "blue")+ # line for surface of the water
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #Line for dry reach; color gets rid of border
    geom_line(aes(y = Max_Depth_Site_m+0.1), color = "brown")+ #line for max depth
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3, shape = 21)+ #need shape here if not doing site type
  scale_y_reverse(breaks = c(0, 0.5, 1, 1.5, 2, 2.5))+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 12),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)",
       y = "Depth (m)", fill = "DO \n (% sat)")+
  scale_x_continuous(breaks = c(0, 150, 300)) +
scale_fill_distiller(palette = "Spectral", direction = -1)

do_S1_C1


#### Stack toghether
# sensors_S1_C1 <- cond_S1_C1 / temp_S1_C1 / do_S1_C1

sensors_S1_C1 <- cowplot::plot_grid(cond_S1_C1, temp_S1_C1, do_S1_C1, labels = c("a", "b", "c"), ncol = 1)

sensors_S1_C1

#ggsave("MS_draft_figures/SpCond_S1-C1.png", cond_S1_C1, width = 9.5, height = 5.5, units = "in")


```
 

S1 to P2 By date profiles for Temp, DO, Cond

```{r}
### Date levels
levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

##COnd 
SpCond_fig <- sensors |> 
    mutate(Date1 = format(Date, "%d %b")) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  ggplot(aes(x = Distance, y = Depth_m, color = SpCond_uScm))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3)+
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "Depth (m)", color = "Sp. Cond (uS/cm)")+
  scale_x_continuous(breaks = c(0, 600, 1200)) +
  scale_color_distiller(palette = "Spectral", direction = -1, breaks = c(25,75,125))

SpCond_fig


##Temp 
Temp_fig <- sensors |> 
    mutate(Date1 = format(Date, "%d %b")) |> 
    filter(!is.na(Temp_C)) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  ggplot(aes(x = Distance, y = Depth_m, color = Temp_C))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3)+ 
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "Depth (m)", color = "Temp (C)")+
  scale_x_continuous(breaks = c(0, 600, 1200)) +
  scale_color_distiller(palette = "Spectral", direction = -1)

Temp_fig


##DO 
DO_fig <- sensors |> 
  filter(!is.na(DOsat_percent)) |> 
    mutate(Date1 = format(Date, "%d %b")) |> 
    mutate(Dry_start = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_start, NA),
         Dry_end = ifelse(Depth_m == 0.1 & Site_code == "S1", Dry_end, NA)) |> #so just one row has info for dry start and end, was having issues where laying multiple rectangles for more observations affected shading color
  ggplot(aes(x = Distance, y = Depth_m, color = DOsat_percent))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 1, fill = "gray", color = NA )+ #color gets rid of border
  facet_wrap(~factor(Date1, levels = levels_db), scales = "fixed", nrow = 1)+
  geom_point(size = 3)+ 
  scale_y_reverse()+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "Depth (m)", color = "DO (% sat)")+
  scale_x_continuous(breaks = c(0, 600, 1200)) +
  scale_color_distiller(palette = "Spectral", direction = -1, breaks = c(25,75,125))

DO_fig

## put them together
library(patchwork)
# sensors_S1_P2 <- Temp_fig / DO_fig / SpCond_fig

sensors_S1_P2 <- cowplot::plot_grid(SpCond_fig, Temp_fig, DO_fig, labels = c("a", "b", "c"), ncol = 1)

sensors_S1_P2
# ggsave("../Figures/sensors_S1_P2_SI_fig.png", sensors_S1_P2, width = 11, height = 8, units = "in")



```


## Heatmaps for sites with CTD casts 


make a function 
adapted from: https://github.com/CareyLabVT/Reservoirs/blob/master/Data/DataAlreadyUploadedToEDI/EDIProductionFiles/Heatmap_EDI_function.R

```{r}

##### Function #
heatmap_EDI <- function(data, reservoir, site_code, z){
  
  # load packages
  pacman::p_load(tidyverse, lubridate, akima, reshape2, 
               gridExtra, grid, colorRamps, RColorBrewer, cowplot, rLakeAnalyzer)
  
  #find thermocline data
thermocline_data <- data |> 
  filter(Site_code == site_code) |> 
  select(Date, Depth_m, Temp_C) |> 
  pivot_wider(names_from = Depth_m, values_from = Temp_C, values_fn = list(Temp_C = mean)) |> 
  rename(datetime = Date)

colnames(thermocline_data)[-1] = paste0('wtr_',colnames(thermocline_data)[-1])


thermocline_depths <- ts.thermo.depth(thermocline_data, na.rm = TRUE)

thermocline_depths <- thermocline_depths |> 
  rename(Date = datetime)
  
  #subset to relevant data
  fp_new <- data %>%
    filter(Reservoir %in% reservoir & Site_code %in% site_code) %>%
    select(Date, Depth_m, {{z}}) 
  
  
  # Create title for plot
  fig_title <- paste(reservoir, "Site", site_code, z, sep = " ")
  
  interp <- interp(x=as.numeric(fp_new$Date), y = fp_new$Depth_m, z = unlist(fp_new[z]),
                   #xo = seq(min(fp_new$DOY), max(fp_new$DOY), by = .1), 
                   xo = seq(min(fp_new$Date), max(fp_new$Date), by = "day"),
                   yo = seq(min(fp_new$Depth_m), max(fp_new$Depth_m), by = 0.1),
                   extrap = T, linear = T, duplicate = "strip")
  interp <- interp2xyz(interp, data.frame=T)
  
  interp<-interp%>%
    mutate(Date=as.Date(x, origin = "1970-01-01"))
  
  
  p1 <- ggplot(interp, aes(x=Date, y=y))+
    geom_raster(aes(fill=z))+
    scale_y_reverse(expand = c(0,0))+
    scale_x_date(expand = c(0, 0)) +
    ## thermocline lines
  geom_line(data = thermocline_depths, aes(x=Date, y=thermo.depth, z=NULL), color = "black", lwd = 1)+
  geom_point(data = thermocline_depths, aes(x=Date, y=thermo.depth, z=NULL), pch = 21, size = 2, color = "white", fill = "black")+
    ##sampling points
    geom_point(data = fp_new, aes(x = Date, y = 0.1, z = NULL), pch = 25, size = 3, fill = "black")+ 
    scale_fill_gradientn(colours = blue2green2red(60), na.value="gray")+
    labs(x = "Date", y = "Depth (m)", title = fig_title,fill=(z))+
    theme_bw()
  
  return(p1)
  
}



#### Site P2 heatmap
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "P2", z = "Temp_C")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "P1", z = "Temp_C")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "C2", z = "Temp_C")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "P2", z = "SpCond_uScm")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "P1", z = "SpCond_uScm")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "C2", z = "SpCond_uScm")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "P2", z = "DO_mgL")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "P1", z = "DO_mgL")
heatmap_EDI(data = sensors, reservoir = "CCR", site_code = "C2", z = "DO_mgL")


```

calc thermocline by dates

```{r}
library(rLakeAnalyzer)

## P2 thermocline
p2_temp <- sensors |> 
  filter(Site_code == "P2") |> 
  select(Date, Depth_m, Temp_C) |> 
  pivot_wider(names_from = Depth_m, values_from = Temp_C, values_fn = list(Temp_C = mean)) |> 
  rename(datetime = Date)

colnames(p2_temp)[-1] = paste0('wtr_',colnames(p2_temp)[-1])

p2_thermocline <- ts.thermo.depth(p2_temp, na.rm = TRUE)

## P1 thermocline
p1_temp <- sensors |> 
  filter(Site_code == "P1") |> 
  select(Date, Depth_m, Temp_C) |> 
  pivot_wider(names_from = Depth_m, values_from = Temp_C, values_fn = list(Temp_C = mean)) |> 
  rename(datetime = Date)

colnames(p1_temp)[-1] = paste0('wtr_',colnames(p1_temp)[-1])

p1_thermocline <- ts.thermo.depth(p1_temp, na.rm = TRUE)


## C2 thermocline
c2_temp <- sensors |> 
  filter(Site_code == "C2") |> 
  select(Date, Depth_m, Temp_C) |> 
  pivot_wider(names_from = Depth_m, values_from = Temp_C, values_fn = list(Temp_C = mean)) |> 
  rename(datetime = Date)

colnames(c2_temp)[-1] = paste0('wtr_',colnames(c2_temp)[-1])

c2_thermocline <- ts.thermo.depth(c2_temp, na.rm = TRUE)



```







