---
title: "Breakpoints"
output: html_document
date: "2025-07-21"
---

## load packages and read in data
```{r}
## packages 
library(ggpubr) # for ggdensity
library(tidyverse)
library(patchwork) # so you can arrange figures by "/" or "|"

## read in chem data
chem <- read_csv("../Data/chemistry_joined.csv")   

## read in chl-a data
ccr_chla <- read.csv("../Data/CCR_chla.csv") |> 
  mutate(Date = as.Date(Date))

chem_chla <- full_join(chem, ccr_chla, by = c("Reservoir", "Site", "Date", "Depth_m")) |> 
  select(-Pheo_ugL)


```



##look at all the DOM comp

```{r}
#DOM comp options
levels <- c("BIX", "HIX", "FI", "Peak_A", "Peak_T", "A_T", "a254_m", "SUVA254")
levels <- c("BIX", "HIX", "A_T", "SUVA254")
#all variable options
levels <- c("DOC_mgL", "BIX", "HIX", "d18O_VSMOW", "d2H_VSMOW", "D_excess")
levels <- c("DOC_mgL", "DON_mgL", "BIX", "HIX", "A_T", "NO3NO2_ugL", "NH4_ugL", "SRP_ugL","D_excess")


#Across dates
chem_chla |> 
  pivot_longer(-c(1:8)) |> 
  # filter(!Site %in% c(50,88,90)) |> #if wanting to zoom in on S1 - C1 transition
  filter(name %in% levels) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
   geom_point(shape = 21, size = 4) +
  facet_wrap(~factor(name, levels = levels), scales = "free_y")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))


```


## SI figure of chem variables by date

```{r}
levels <- c("DOC_mgL", "BIX", "HIX", "NO3NO2_ugL", "D_excess")

levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

#By dates
Chem_by_date_SI_fig <- chem_chla |> 
  pivot_longer(-c(1:8)) |>  
  # filter(!Site %in% c(50,88,90)) |> #if wanting to zoom in on S1 - C1 transition
  filter(name %in% levels) |> 
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point(shape = 21, size = 4) + #shape = 21,
  #geom_smooth()+ # add ', warning=FALSE' to chunk to see plot
  facet_grid(factor(name, levels = levels)~factor(Date1, levels = levels_db), scales = "free_y")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    axis.text.x = element_text(angle = 45, hjust = 1), #can make angle = 45 and hjust = 1 to shift x label
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 600, 1200))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

Chem_by_date_SI_fig

# ggsave("../Figures/Chem_by_Date_SI.png", height = 8, width = 11, units = "in")


```



## Make nice plots of each variable

```{r}

#Faceting
chem_chla |> 
  pivot_longer(-c(1:8)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  geom_point(shape = 21, size = 3) + #shape = 21,
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
    facet_wrap(~name, scales = "free_y")+
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))



#### just one variable
#BIX  # bix_clean <- 
chem_chla |> 
  ggplot(aes(x = Distance, y = BIX, fill = Depth_m))+
  #geom_point(shape = 21, size = 3) + #shape = 21,
  geom_jitter(size = 3, shape = 21, width = 10, height = 0)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "BIX", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
   scale_fill_gradient2(low = "red",  high ="blue",
                        midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))
  # scale_fill_gradient2(
  #   low = "red",
  #   high = "blue",
  #   midpoint = 6,
  #   guide = "colourbar",
  #   breaks = c(3, 6, 9, 10, 15),   # show ticks beyond 10
  #   limits = c(0, 15),             # extend legend to 15
  #   oob = 
  #   oob = scales::squish           # cap colors at 10
  # )


```




########################### KRUSKAL wallis ###################################

## Normality test

```{r}
#### normality
  ##https://www.sthda.com/english/wiki/normality-test-in-r

ggdensity(chem_chla$BIX, xlab = "BIX", main = "Density plot of BIX in CCR")
shapiro.test(chem_chla$BIX) # p-values < 0.05 means data is not normally distributed
ggdensity(chem_chla$DOC_mgL, xlab = "DOC (mg/L)", main = "Density plot of DOC in CCR")
shapiro.test(chem_chla$DOC_mgL) 
ggdensity(chem_chla$d2H_VSMOW, xlab = "dH2", main = "Density plot of dH2 in CCR")
shapiro.test(chem_chla$d2H_VSMOW) 


```




## Define site types for boxplots

```{r}
## first add site type to chem data frame 
chem_kruskal <- chem_chla |> 
  mutate(Site_Type = ifelse(Site_code %in% c("S1", "S2"), "Stream", NA),
         Site_Type = ifelse(Site_code %in% c("B1", "B2"), "Backwater", Site_Type),
         Site_Type = ifelse(Site_code %in% c("C1", "C2"), "Cove", Site_Type),
         Site_Type = ifelse(Site_code %in% c("P1", "P2"), "Pelagic", Site_Type)
         )

```


## Make function for KW plots

```{r}
library(tidyverse)
library(FSA)
library(rcompanion)
library(ggpubr)
library(rlang)

#### Function

make_kruskal_dunn_plot <- function(df, response_var, group_var = "Site_Type", level_order = c("Stream", "Backwater", "Cove", "Pelagic")) {
  
  group_sym <- rlang::sym(group_var)
  response_sym <- rlang::sym(response_var)
  
  formula <- as.formula(paste(response_var, "~", group_var))
  kruskal <- kruskal.test(formula, data = df)
  dunn <- FSA::dunnTest(formula, data = df)
  dunn_letters <- dunn$res
  
  dunn_letters_list <- rcompanion::cldList(
    comparison = dunn_letters$Comparison,
    p.value = dunn_letters$P.adj,
    threshold = 0.05
  )
  
  df_plot <- df %>%
    left_join(dunn_letters_list, by = setNames("Group", group_var))
  
  # Calculate dynamic label position
  y_max <- max(df[[response_var]], na.rm = TRUE)
  label_y <- y_max + 0.01 * abs(y_max)  # Add 10% buffer above max
  
  p <- ggplot(df_plot, aes(x = factor(!!group_sym, levels = level_order), y = !!response_sym)) +
    geom_boxplot(outlier.alpha = 0) +
    geom_jitter(width = 0.2) +
    stat_compare_means(method = "kruskal.test", label.y = label_y * 1.1, label.x = 1.3, size = 4) +
    geom_text(aes(label = Letter), y = label_y * 1.05, size = 5) +
    theme_bw() +
    theme(#axis.text.x = element_text(angle = 0, hjust = 0), #can make angle = 45 and hjust = 1 to shift x label
          text = element_text(size = 12),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    labs(x = "Site Type", y = response_var)
  
  return(p)
  
} #end of function

```


## Run function to make all boxplots

```{r}

#### Run function 
response_vars <- c(
                   "BIX", "HIX", "A_T", "SUVA254", 
                   "DOC_mgL", "DN_mgL", "DON_mgL",
                   "NH4_ugL", "NO3NO2_ugL", "SRP_ugL",
                   "Chla_ugL",
                   "d18O_VSMOW", "d2H_VSMOW", "D_excess"
                   )  

# Generate plots for each variable
plots <- lapply(response_vars, function(var) {
  make_kruskal_dunn_plot(chem_kruskal, response_var = var)
})

# Optionally name the plots
names(plots) <- response_vars



```


## DOM boxplots

```{r}
#view just one
# plots$BIX

#make a few plots in groups 
library(gridExtra)
gridExtra::grid.arrange(plots$BIX, plots$HIX, plots$A_T, plots$SUVA254, nrow = 1) #EEM
gridExtra::grid.arrange(plots$DOC_mgL, plots$DON_mgL, nrow = 1) #DOM

### DOM plot for MS 

DOM_boxplots_MS <- cowplot::plot_grid(plots$DOC_mgL, plots$BIX, plots$HIX, plots$A_T, plots$SUVA254, labels = c("a", "b", "c", "d", "e"), nrow = 2)

DOM_boxplots_MS

# ggsave("../Figures/DOM_boxplot_MS.png", DOM_boxplots_MS, height = 6, width = 8, units = "in")


```


## Nutrients, chla, Isotopes boxplots

```{r}

gridExtra::grid.arrange(plots$NO3NO2_ugL, plots$NH4_ugL, plots$DN_mgL, plots$SRP_ugL, nrow = 1) #Nutrients
gridExtra::grid.arrange(plots$d18O_VSMOW, plots$d2H_VSMOW, plots$D_excess, nrow = 1) #Isotopes


##nutrient boxplots for SI
nutrient_chla_boxplots_SI <- cowplot::plot_grid(plots$NO3NO2_ugL, plots$NH4_ugL, 
                                           plots$SRP_ugL, plots$Chla_ugL, 
                                           labels = c("a", "b", "c", "d"), nrow = 1)

nutrient_chla_boxplots_SI

 # ggsave("../Figures/Nutrient_boxplot_SI.png", nutrient_boxplots_SI, height = 3, width = 8.5, units = "in")


```





##Some boxplot summary stats

DOC

```{r}

chem_kruskal |> 
  # dplyr::select(Site_Type, DOC_mgL, HIX, BIX, NO3NO2_ugL, D_excess) |> 
  dplyr::select(Site_Type, NO3NO2_ugL) |> 
  group_by(Site_Type) %>%
  summarise(across(
    .cols = where(is.numeric),
    .fns = list(
      mean   = ~mean(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE),
      min    = ~min(.x, na.rm = TRUE),
      max    = ~max(.x, na.rm = TRUE),
      range  = ~max(.x, na.rm = TRUE) - min(.x, na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  ))


## DOC plot over time
doc_by_day <- chem |> 
  ggplot(aes(x = Distance, y = DOC_mgL, fill = Depth_m))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point(shape = 21, size = 4) +
  facet_wrap(~Date, scales = "fixed")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

doc_by_day
# plotly::ggplotly(doc_by_day)


#DOC range within pelagic sites
chem_kruskal |> filter(Site_Type == "Pelagic") |> 
  dplyr::select(Date, Site_code, DOC_mgL) |> 
  group_by(Date, Site_code) |> 
  summarise(across(
    .cols = where(is.numeric),
    .fns = list(
      mean   = ~mean(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE),
      min    = ~min(.x, na.rm = TRUE),
      max    = ~max(.x, na.rm = TRUE),
      range  = ~max(.x, na.rm = TRUE) - min(.x, na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  )) |> 
  arrange(Site_code)

```



