---
title: "Breakpoints"
output: html_document
date: "2025-07-21"
---

## load packages and read in data
```{r}
## packages 
library(ggpubr) # for ggdensity
library(tidyverse)
library(patchwork) # so you can arrange figures by "/" or "|"
library(gridExtra)


## read in chem data
chem <- read_csv("../Data/chemistry_joined_sensor_hydro.csv")   

```



## SI figure of chem variables by date

```{r}
levels <- c("DOC_mgL", "BIX", "HIX")

levels_db <- c("22 May", "19 Jun", "11 Jul", "14 Aug", "16 Sep", 
               "30 Sep", "28 Oct", "17 Dec", "26 Feb", "16 Apr")

#By dates
Chem_by_date_SI_fig <- chem |> 
  pivot_longer(-c(1:7)) |>  
  # filter(!Site %in% c(50,88,90)) |> #if wanting to zoom in on S1 - C1 transition
  filter(name %in% levels) |> 
  mutate(Date1 = format(Date, "%d %b")) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point(shape = 21, size = 4) + #shape = 21,
  #geom_smooth()+ # add ', warning=FALSE' to chunk to see plot
  facet_grid(factor(name, levels = levels)~factor(Date1, levels = levels_db), scales = "free_y")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    axis.text.x = element_text(angle = 45, hjust = 1), #can make angle = 45 and hjust = 1 to shift x label
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 600, 1200))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

Chem_by_date_SI_fig

# ggsave("../Figures/Chem_by_Date_SI.png", Chem_by_date_SI_fig, height = 8, width = 11, units = "in")


```



## Make nice plots of each variable

```{r}

#Faceting
chem |> 
  pivot_longer(-c(1:8)) |> 
  ggplot(aes(x = Distance, y = value, fill = Depth_m))+
  geom_point(shape = 21, size = 3) + #shape = 21,
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
    facet_wrap(~name, scales = "free_y")+
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))



#### just one variable
#BIX  # bix_clean <- 
chem |> 
  ggplot(aes(x = Distance, y = BIX, fill = Depth_m))+
  #geom_point(shape = 21, size = 3) + #shape = 21,
  geom_jitter(size = 3, shape = 21, width = 10, height = 0)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", y = "BIX", fill = "Depth (m)",
       shape = "Site Type")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
   scale_fill_gradient2(low = "red",  high ="blue",
                        midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))
  # scale_fill_gradient2(
  #   low = "red",
  #   high = "blue",
  #   midpoint = 6,
  #   guide = "colourbar",
  #   breaks = c(3, 6, 9, 10, 15),   # show ticks beyond 10
  #   limits = c(0, 15),             # extend legend to 15
  #   oob = 
  #   oob = scales::squish           # cap colors at 10
  # )


```




########################### KRUSKAL wallis ###################################

## Normality test

```{r}
#### normality
  ##https://www.sthda.com/english/wiki/normality-test-in-r

ggdensity(chem$BIX, xlab = "BIX", main = "Density plot of BIX in CCR")
shapiro.test(chem$BIX) # p-values < 0.05 means data is not normally distributed
ggdensity(chem$DOC_mgL, xlab = "DOC (mg/L)", main = "Density plot of DOC in CCR")
shapiro.test(chem$DOC_mgL) 
ggdensity(chem$d2H_VSMOW, xlab = "dH2", main = "Density plot of dH2 in CCR")
shapiro.test(chem$d2H_VSMOW) 


```




## Define site types for boxplots

```{r}
## first add site type to chem data frame 
chem_kruskal <- chem |> 
  mutate(Site_Type = ifelse(Site_code %in% c("S1", "S2"), "Stream", NA),
         Site_Type = ifelse(Site_code %in% c("B1", "B2"), "Back", Site_Type),
         Site_Type = ifelse(Site_code %in% c("C1", "C2"), "Cove", Site_Type),
         Site_Type = ifelse(Site_code %in% c("P1", "P2"), "Pelagic", Site_Type)
         )

```


## Make function for KW plots

```{r}

library(tidyverse)
library(FSA)
library(rcompanion)
library(ggpubr)
library(rlang)

site_colors <- c("Stream" = "#30123BFF",
                 "Back" = "#1BD0D5FF", 
                 "Cove" = "#D2E935FF", 
                 "Pelagic" = "#DB3A07FF" )

make_kruskal_dunn_plot <- function(df, response_var, 
                                   response_var_label = NULL, 
                                   group_var = "Site_Type", 
                                   level_order = c("Stream", "Back", "Cove", "Pelagic")) {
  
  group_sym <- rlang::sym(group_var)
  response_sym <- rlang::sym(response_var)
  
  formula <- as.formula(paste(response_var, "~", group_var))
  kruskal <- kruskal.test(formula, data = df)
  dunn <- FSA::dunnTest(formula, data = df)
  dunn_letters <- dunn$res
  
  dunn_letters_list <- rcompanion::cldList(
    comparison = dunn_letters$Comparison,
    p.value = dunn_letters$P.adj,
    threshold = 0.05
  )
  
  df_plot <- df %>%
    left_join(dunn_letters_list, by = setNames("Group", group_var))
  
  # Calculate dynamic label position
  y_max <- max(df[[response_var]], na.rm = TRUE)
  label_y <- y_max + 0.01 * abs(y_max)
  
  # Clean p-value label
  p_val <- kruskal$p.value
  p_label <- if (p_val < 0.001) {
    "p < 0.001"
  } else if (p_val < 0.01) {
    "p < 0.01"
  } else if (p_val < 0.05) {
    "p < 0.05"
  } else {
    paste0("p = ", round(p_val, 3))
  }
  
  p <- ggplot(df_plot, aes(x = factor(!!group_sym, levels = level_order), y = !!response_sym)) +
    geom_boxplot(aes(fill = factor(!!group_sym, levels = level_order)), outlier.alpha = 0, alpha = 0.5) +
    geom_jitter(width = 0.2) +
    annotate("text", x = 1.8, y = label_y * 1.1, label = paste("KW", p_label, sep = " "), size = 4) +
    geom_text(aes(label = Letter), y = label_y * 1.05, size = 5) +
    scale_fill_manual(values = site_colors) +
        theme_bw() +
    theme(
      text = element_text(size = 14),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "none"
    ) +
    labs(x = "Site Type", 
         y = if (!is.null(response_var_label)) response_var_label else response_var
         )

  
  # Return plot and stats as a list
  return(list(
    plot = p,
    kruskal = kruskal,
    dunn = dunn
  ))
  
} # end of function



```


Test function works 

```{r}
##run just one
bix_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "BIX")
bix_kw$plot
bix_kw$kruskal
bix_kw$dunn

#just doc testing label
make_kruskal_dunn_plot(df = chem_kruskal, response_var = "DOC_mgL")

make_kruskal_dunn_plot(df = chem_kruskal, response_var = "DOC_mgL", response_var_label = "DOC (mg/L)")

```



## Run function to make all boxplots

```{r}

#define what plots to make
response_vars <- c(
                   "BIX", "HIX", "A_T", "SUVA254", 
                   "DOC_mgL", "DN_mgL", "DON_mgL",
                   "NH4_ugL", "NO3NO2_ugL", "SRP_ugL",
                   "Chla_ugL",
                   "d18O_VSMOW", "d2H_VSMOW", "D_excess"
                   )  

# Generate results for each variable
results <- lapply(response_vars, function(var) {
  make_kruskal_dunn_plot(chem_kruskal, response_var = var)
})

names(results) <- response_vars


# Plot as before - just add $plot
gridExtra::grid.arrange(results$DOC_mgL$plot, results$DON_mgL$plot, 
                        results$BIX$plot, results$HIX$plot, results$A_T$plot, results$SUVA254$plot, nrow = 2)


gridExtra::grid.arrange(results$NO3NO2_ugL$plot, results$NH4_ugL$plot, results$DN_mgL$plot, 
                        results$SRP_ugL$plot, results$Chla_ugL$plot, nrow = 1) #Nutrients

gridExtra::grid.arrange(results$d18O_VSMOW$plot, results$d2H_VSMOW$plot, results$D_excess$plot, nrow = 1) #Isotopes





# View stats for specific variables
results$BIX$kruskal
results$BIX$dunn

results$DOC_mgL$kruskal
results$DOC_mgL$dunn






```


## DOM boxplots

```{r}
#### Make DOM boxplots with nice labels for MS

##DOC
doc_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "DOC_mgL", response_var_label = "DOC (mg/L)")
doc_kw$kruskal

##BIX
bix_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "BIX")
bix_kw$kruskal

##HIX
hix_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "HIX")
hix_kw$kruskal

##AT
AT_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "A_T", response_var_label = "Peak A:T Ratio ")
AT_kw$kruskal

##SUVA 254
suva_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "SUVA254", response_var_label = "SUVA254")
suva_kw$kruskal

### DOM plot for MS 

DOM_boxplots_MS <- cowplot::plot_grid(doc_kw$plot, bix_kw$plot, hix_kw$plot, AT_kw$plot, suva_kw$plot,
                                      # plots$DOC_mgL, plots$BIX, plots$HIX, plots$A_T, plots$SUVA254, 
                                      
                                      labels = c("a", "b", "c", "d", "e"), nrow = 2)

DOM_boxplots_MS

# ggsave("../Figures/DOM_boxplot_MS.png", DOM_boxplots_MS, height = 6, width = 8, units = "in")


```




## Nutrients, chla, Isotopes boxplots

```{r}
#Make nice boxplots of nutrients and chla for SI 
##NO3
no3_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "NO3NO2_ugL", response_var_label = "NO3 (ug/L)")
no3_kw$kruskal

##NH4
nh4_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "NH4_ugL", response_var_label = "NH4 (ug/L)")
nh4_kw$kruskal

##SRP
srp_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "SRP_ugL", response_var_label = "SRP (ug/L)")
srp_kw$kruskal

##Chl-a
chla_kw <- make_kruskal_dunn_plot(df = chem_kruskal, response_var = "Chla_ugL", response_var_label = "Chl-a (ug/L)")
chla_kw$kruskal



##nutrient boxplots for SI
nutrient_chla_boxplots_SI <- cowplot::plot_grid(no3_kw$plot, nh4_kw$plot, srp_kw$plot, chla_kw$plot, 
                                           labels = c("a", "b", "c", "d"), nrow = 2)

nutrient_chla_boxplots_SI

ggsave("../Figures/NutChla_boxplot_SI.png", nutrient_chla_boxplots_SI, height = 6, width = 8, units = "in")


```

## KW stats

```{r}

doc_kw$kruskal

bix_kw$kruskal
  
hix_kw$kruskal

AT_kw$kruskal

suva_kw$kruskal
  
no3_kw$kruskal

chla_kw$kruskal
  
```



##Some boxplot summary stats

DOC

```{r}

chem_kruskal |> 
  # dplyr::select(Site_Type, DOC_mgL, HIX, BIX, NO3NO2_ugL, D_excess) |> 
  dplyr::select(Site_Type, NO3NO2_ugL) |> 
  group_by(Site_Type) %>%
  summarise(across(
    .cols = where(is.numeric),
    .fns = list(
      mean   = ~mean(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE),
      min    = ~min(.x, na.rm = TRUE),
      max    = ~max(.x, na.rm = TRUE),
      range  = ~max(.x, na.rm = TRUE) - min(.x, na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  ))


## DOC plot over time
doc_by_day <- chem |> 
  ggplot(aes(x = Distance, y = DOC_mgL, fill = Depth_m))+
  geom_rect(aes(xmin = Dry_start, xmax = Dry_end, ymin = -Inf, ymax = Inf), 
            alpha = 0.1, fill = "gray", color = NA )+ #color gets rid of border
  geom_point(shape = 21, size = 4) +
  facet_wrap(~Date, scales = "fixed")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 18),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  labs(x= "Distance from Stream (m)", fill = "Depth (m)")+
  scale_x_continuous(breaks = c(0, 500, 1000, 1500))+ 
  scale_fill_gradient2(low = "red",  high ="blue",
                       midpoint = 6,  guide = "colourbar", breaks = c(3,6,9, 15))

doc_by_day
# plotly::ggplotly(doc_by_day)


#DOC range within pelagic sites
chem_kruskal |> filter(Site_Type == "Pelagic") |> 
  dplyr::select(Date, Site_code, DOC_mgL) |> 
  group_by(Date, Site_code) |> 
  summarise(across(
    .cols = where(is.numeric),
    .fns = list(
      mean   = ~mean(.x, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE),
      min    = ~min(.x, na.rm = TRUE),
      max    = ~max(.x, na.rm = TRUE),
      range  = ~max(.x, na.rm = TRUE) - min(.x, na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  )) |> 
  arrange(Site_code)

```



